.TH WATCHDOG.CONF 5 "September 1998"
.UC 4
.SH NAME
watchdog.conf \- configuration file for watchdog.8
.SH DESCRIPTION
This file carries all configuartion option for the Linux software watchdog.
Each option has to be written on a line for itself. Comments start with ´#´.
Blanks are ignored except after the ´=´ sign. An empty text after the ´=´
sign disables the feature as long as that makes sense.

.SH OPTIONS
Available  options are the following:
.TP
interval = <interval>
Set the interval between two writes to the softdog device. The kernel
drivers expects a write command every minute. Otherwise the system will be
rebooted. Default value is 10 seconds. An interval of more than a minute can
only be used with the -f commandline option.
.TP
max-load-1 = <load1>
Set the maximal allowed load average for a 1 minute span. Once this load
average is reached the system is rebooted. Default value is 12. Be careful
not to this parameter too low. To set a value less then the predefined
minimal value of 2, you have to use the -f commandline option.
.TP
max-load-5 = <load5>
Set the maximal allowed load average for a 5 minute span. Once this load
average is reached the system is rebooted. Default value is 9. Be careful
not to this parameter too low. To set a value less then the predefined
minimal value of 2, you have to use the -f commandline option.
.TP
max-load-15 = <load15>
Set the maximal allowed load average for a 15 minute span. Once this load
average is reached the system is rebooted. Default value is 6. Be careful
not to this parameter too low. To set a value less then the predefined
minimal value of 2, you have to use the -f commandline option.
.TP
max-temperature = <temp>
Set the maximal allowed temperature. Once this temperature is reached the
system is halted. Default value is 120. There is no unit conversion. So make
sure you use the same unit as your hardware. Watchdog will issue warnings
once the tempearture increases 90%, 95% and 98% of this temperature.
.TP
watchdog-device = <device>
Set the watchdog device name. Default is disable keep alive suppport.
.TP
temperature-device = <temp-dev>
Set the temperature device name. Default is disable temperature checking.
.TP
file = <filename>
Set file name for file mode.

Note that this option can be given as often as you like to check several
files.
.TP
change = <mtime> Set the change interval time for file mode. This options
always belongs to the active filename, that is when finding a ´change =´
line watchdog assumes it belongs to the most recently read ´file =´ line.
They don't neccessarily have to follow each other directly. But you cannot
specify a ´change =´ before a ´file =´.

The default is to only stat the file and don't look for changes.
.TP
ping = <ip-addr>
Set IP address for ping mode

This option also can be used more often than once to check different
connections.
.TP
test-binary = <testbin>
Execute the given binary to do some user defined tests.
.TP
repair-binary = <repbin>
Execute the given binary in case of a problem instead of shutting down the
system.
.TP
admin = <mail-address>
Email address to send admin mail to. That is, who shall be notified that the
machine is being halted.
.TP
.SH FILES
.nf
/etc/watchdog.conf  The watchdog configuration file
.fi
.SH "SEE ALSO"
.BR watchdog "(8)
